---
#determine postgres major and minor versions
pg_major_version: "{% if postgresql_version is defined and postgresql_version != omit %}{{postgresql_version.split('.')[0]}}{% else %}9{% endif %}"
pg_minor_version: "{% if postgresql_version is defined and postgresql_version != omit %}{{postgresql_version.split('.')[1]}}{% else %}6{% endif %}"

#postgres bin PATH
pg_bin_path: "{% if pg_major_version | int < 10 %}/usr/pgsql-{{pg_major_version}}.{{pg_minor_version}}/bin{%else%}/usr/pgsql-{{pg_major_version}}/bin{%endif%}"

#postgres profile.d path
pg_profile_path: "{% if pg_major_version | int < 10 %}/etc/profile.d/postgres{{pg_major_version}}{{pg_minor_version}}-bin.sh{%else%}/etc/profile.d/postgres{{pg_major_version}}-bin.sh{%endif%}"