---
sudo: required

language: perl

services:
  - docker

before_install:
  - docker-compose up traffic_ops_build

---
sudo: required

language: java

services:
  - docker

before_install:
  - docker-compose up traffic_monitor_build
