---
sudo: required

language: perl

services:
  - docker

before_install:
  - docker-compose -f infrastructure/docker/build/Dockerfile-traffic_ops up traffic_ops_build

---
sudo: required

language: java

services:
  - docker

before_install:
  - docker-compose -f infrastructure/docker/build/Dockerfile-traffic_monitor up traffic_monitor_build
