---
sudo: required

language: java

services:
  - docker

before_install:
  - docker-compose -f infrastructure/docker/build/docker-compose.yml up traffic_ops_build

---
sudo: required

language: java

services:
  - docker

before_install:
  - docker-compose -f infrastructure/docker/build/docker-compose.yml up traffic_monitor_build
