apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: Apache Traffic Control

deploy:
  kubectl:
    manifests:
      - infrastructure/skaffold/postgres/*.yaml
      - infrastructure/skaffold/influxdb/*.yaml
      - infrastructure/skaffold/riak/*.yaml
      - infrastructure/skaffold/ats/*.yaml
