version: '2'

volumes:
  sync:

services:
  # dataimport reads data from an existing traffic_ops server running mysql thru the API
  dataimport:
    build:
        context: .
        dockerfile: Dockerfile-traffic_ops-client
    restart: "no"
    environment:
      - TO_USER
      - TO_PASSWORD
      - TO_SERVER

    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d

  # mysql_host loads mysql data locally and provides direct access for pgloader
  mysql_host:
    image: mysql:5.6
    restart: "no"
    environment:
      - MYSQL_DATABASE=traffic_ops_db
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD=twelve
      - MYSQL_USER=to_user
    depends_on:
      - dataimport
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d

  # postgres_host provides a postgres data to import data to
  postgres_host:
    build:
      context: ..
      dockerfile: pg-migration/Dockerfile-postgres
    restart: "no"
    environment:
      - POSTGRES_DB=traffic_ops
      - POSTGRES_PASSWORD=twelve
      - POSTGRES_USER=traffic_ops
    volumes:
      - /opt/traffic_ops-db:/var/lib/postgresql/data
    ports:
      - 5432

  # pgloader converts the data from mysql to postgres
  pgloader:
    build:
      context: ..
      dockerfile: pg-migration/Dockerfile-pgloader
    restart: "no"
    depends_on:
      - mysql_host
      - postgres_host
    environment:
      - MYSQL_HOST=mysql_host
      - MYSQL_DATABASE=traffic_ops_db
      - MYSQL_PASSWORD=twelve
      - MYSQL_USER=to_user
      - POSTGRES_HOST=postgres_host
      - POSTGRES_DB=traffic_ops
      - POSTGRES_PASSWORD=twelve
      - POSTGRES_USER=traffic_ops
    volumes:
      - sync:/sync

  # convert runs necessary post-import conversion(s) in postgres
  convert:
    build:
      context: ..
      dockerfile: pg-migration/Dockerfile-convert
    restart: "no"
    depends_on:
      - postgres_host
    environment:
      - POSTGRES_HOST=postgres_host
      - POSTGRES_DB=traffic_ops
      - POSTGRES_PASSWORD=twelve
      - POSTGRES_USER=traffic_ops
    volumes:
      - sync:/sync
