# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Go Unit Tests

on:
  push:
    paths:
      - grove/**.go
      - lib/**.go
      - traffic_monitor/**.go
      - traffic_ops/traffic_ops_golang/**.go
      - traffic_ops_ort/atstccfg/**.go
  create:
  pull_request:
    paths:
      - grove/**.go
      - lib/**.go
      - traffic_monitor/**.go
      - traffic_ops/traffic_ops_golang/**.go
      - traffic_ops_ort/atstccfg/**.go
    types: [opened, reopened, edited, synchronize]

jobs:
  grove:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run Grove unit tests
      uses: ./.github/actions/go-test
      with:
        dir: ./grove/...

  lib:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run lib unit tests
      uses: ./.github/actions/go-test
      with:
        dir: ./lib/...

  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run Traffic Monitor unit tests
      uses: ./.github/actions/go-test
      with:
        dir: ./traffic_monitor/...

  ops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run Traffic Ops unit tests
      uses: ./.github/actions/go-test
      with:
        dir: ./traffic_ops/traffic_ops_golang/...

  ort:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run Traffic Ops ORT unit tests
      uses: ./.github/actions/go-test
      with:
        dir: ./traffic_ops_ort/atstccfg/...
